name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t boro215/docker-react .

      - name: Push Docker image
        run: docker push boro215/docker-react

      - name: Generate deployment package
        run: |
          mkdir deploy
          docker run boro215/docker-react sh -c "cp -r /usr/share/nginx/html/* /app/deploy/"
          zip -r deploy.zip deploy/

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-440744218361
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip